ValleyVisionSolution/Pages/ManageProfiles/EditProfilesPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;


namespace ValleyVisionSolution.Pages.ManageProfiles
{
    public class EditProfilesPageModel : PageModel
    {
        
        [BindProperty]
        public FullProfile ProfileToUpdate { get; set; }

        public EditProfilesPageModel()
        {
            ProfileToUpdate = new FullProfile();
        }

        public void loadData()
        {
            ProfileToUpdate = DBClass.SingleProfilesReader(HttpContext.Session.GetInt32("EditedUserID"));
        }

        public IActionResult OnGet(int userid)
        {
            if (HttpContext.Session.GetString("LoggedIn") == "True")
            {
                HttpContext.Session.SetInt32("EditedUserID", userid);
                loadData();
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }
        }

        public IActionResult OnPostUpdateProfile()
        {
            if (ProfileToUpdate.Apartment == null)
            {
                ProfileToUpdate.Apartment = "";
            }
            DBClass.UpdateProfile(ProfileToUpdate);
            DBClass.ValleyVisionConnection.Close();
            return RedirectToPage("/ManageProfiles/ManageProfilesPage");
        }

        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }
    }
}

ValleyVisionSolution/Pages/ManageProfiles/ManageProfilesPage.cshtml.cs
using DocumentFormat.OpenXml.EMMA;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;

namespace ValleyVisionSolution.Pages.ManageProfiles
{
    public class ManageProfilesPageModel : PageModel
    {
        public List<FullProfile> FullProfileList {get ;set;}
        public bool OpenAddProfileModal { get; set; }

        [BindProperty]
        public FullProfile NewProfile { get; set; }
       

        public ManageProfilesPageModel()
        {
            FullProfileList = new List<FullProfile>();
            OpenAddProfileModal = false; //keeps the modal open on page reload if input validations were not successful
        }


        public void loadData() 
        {
            //populate FullProfilesList with FullProfiles
            FullProfileList = DBClass.FullProfilesReader();
            
        }


        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("LoggedIn") == "True" && DBClass.CheckUserType((int)HttpContext.Session.GetInt32("UserID")) == "Admin")
            {
                HttpContext.Session.Remove("InitName");
                loadData();
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }

        }

        public IActionResult OnPostNewProfile()
        {
            if (!ModelState.IsValid)
            {
                // Model state is not valid, return the page with validation errors
                loadData();
                OpenAddProfileModal = true;
                return Page();
            }
            if (NewProfile.Apartment == null)
            {
                NewProfile.Apartment = "";
            }

            DBClass.AddUser(NewProfile);
            loadData();
            ModelState.Clear();
            NewProfile = new FullProfile();

            return Page();
        }

        public IActionResult OnPostDeleteProfile(int userid)
        {
            DBClass.DeleteUser(userid);
            return RedirectToPage("/ManageProfiles/ManageProfilesPage");
        }

        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }

        public IActionResult OnPostPopulateHandler()
        {
            ModelState.Clear();
            NewProfile.UserName = "JamesMad";
            NewProfile.Password = "1234!";
            NewProfile.FirstName = "James";
            NewProfile.LastName = "Madison";
            NewProfile.Email = "maddy@dukes.edu";
            NewProfile.Phone = "5034567980";
            NewProfile.Street = "MLK Way";
            NewProfile.Apartment = "";
            NewProfile.City = "Harrisonburg";
            NewProfile.State = "VA";
            NewProfile.Zip = 22801;
            NewProfile.Country = "U.S.A";

            OpenAddProfileModal = true;

            loadData();


            return Page();
        }

        //public IActionResult OnPostPopulateHandler()
        //{
        //    ModelState.Clear();
        //    PrepareDefaultProfileData();
        //    OpenAddProfileModal = true;
        //    loadData();
        //    return Page();
        //}

        //private void PrepareDefaultProfileData()
        //{
        //    NewProfile.UserName = "JamesMad";
        //    NewProfile.Password = "1234!";
        //    NewProfile.FirstName = "James";
        //    NewProfile.LastName = "Madison";
        //    NewProfile.Email = "maddy@dukes.edu";
        //    NewProfile.Phone = "5034567980";
        //    NewProfile.Street = "MLK Way";
        //    NewProfile.Apartment = "";
        //    NewProfile.City = "Harrisonburg";
        //    NewProfile.State = "VA";
        //    NewProfile.Zip = 22801;
        //    NewProfile.Country = "U.S.A";
        //}


    }
}

ValleyVisionSolution/Pages/ManageProfiles/SingleProfilePage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;

namespace ValleyVisionSolution.Pages.ManageProfiles
{
    public class ProfilePageModel : PageModel
    {
        public FullProfile profileInformation { get; set; }

        public ProfilePageModel()
        {
            profileInformation = new FullProfile();
        }

        public void loadData()
        {
            HttpContext.Session.Remove("InitName");
            profileInformation = DBClass.SingleProfilesReader(HttpContext.Session.GetInt32("UserID"));
        }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("LoggedIn") == "True")
            {
                loadData();
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }
        }

        //Need a get Picture Path method in DB to get it from DB
        //Need to update SQL statements and upload images into the pictures file

        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }
    }
}

ValleyVisionSolution/Pages/ManageProfiles/EditProfilesPage.cshtml
@page
@model ValleyVisionSolution.Pages.ManageProfiles.EditProfilesPageModel
@using FullProfile = ValleyVisionSolution.Pages.DataClasses.FullProfile;
@{
    ViewData["Title"] = "Edit Profile";
}

<!-- Edit Profile Form -->
<div class="modal fade" id="editProfileForm" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form method="post" asp-page="/EditProfilesPage">
                <input type="hidden" name="triggeredBy" id="triggeredBy" value="">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Edit User</h5>
                    <button type="button" class="btn-close" id="closeButton" data-bs-dismiss="modal" aria-label="Close">
                    </button>
                </div>
                <div class="modal-body">

                    <input type="hidden" asp-for="@Model.ProfileToUpdate.UserID">
                   
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <div>Username:</div>
                            <input asp-for="@Model.ProfileToUpdate.UserName" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.UserName"></span>
                        </div>
                        @* <div class="col-md-6">
                            <div>Password:</div>
                            <input asp-for="@Model.ProfileToUpdate.Password" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.Password"></span>
                        </div> *@
                        <div class="col-md-6">
                            <div>First Name:</div>
                            <input asp-for="@Model.ProfileToUpdate.FirstName" type="text" class="form-control" /> 
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.FirstName"></span>
                        </div>
                        <div class="col-md-6">
                            <div>Last Name:</div>
                            <input asp-for="@Model.ProfileToUpdate.LastName" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.LastName"></span>
                        </div>
                        <div class="col-md-6">
                            <div>Email:</div>
                            <input asp-for="@Model.ProfileToUpdate.Email" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.Email"></span>
                        </div>
                        <div class="col-md-6">
                            <div>Phone:</div>
                            <input asp-for="@Model.ProfileToUpdate.Phone" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.Phone"></span>
                        </div>
                        <div class="col-md-6">
                            <div>User Type:</div>
                            <select asp-for="@Model.ProfileToUpdate.UserType" class="form-select">
                                <option value="User">User</option>
                                <option value="Admin">Admin</option>
                            </select>
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.UserType"></span>
                        </div>
                        <div class="col-md-6">
                            <div>Street:</div>
                            <input asp-for="@Model.ProfileToUpdate.Street" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.Street"></span>
                        </div>
                        <div class="col-md-6">
                            <div>Apartment:</div>
                            <input asp-for="@Model.ProfileToUpdate.Apartment" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.Apartment"></span>
                        </div>
                        <div class="col-md-6">
                            <div>City:</div>
                            <input asp-for="@Model.ProfileToUpdate.City" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.City"></span>
                        </div>
                        <div class="col-md-6">
                            <div>State:</div>
                            <input asp-for="@Model.ProfileToUpdate.State" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.State"></span>
                        </div>
                        <div class="col-md-6">
                            <div>Zip:</div>
                            <input asp-for="@Model.ProfileToUpdate.Zip" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.Zip"></span>
                        </div>
                        <div class="col-md-6">
                            <div>Country:</div>
                            <input asp-for="@Model.ProfileToUpdate.Country" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.ProfileToUpdate.Country"></span>
                        </div>
                </div>
                <div class="modal-footer" style="border-top:none">
                    <button type="submit" class="btn btn-primary" asp-page-handler="UpdateProfile">Update</button>
                </div>
            </form>

        </div>
    </div>
</div>
<!-- End Edit Profile Form -->


<script>
    // This script replaces jQuery code with vanilla JS for Bootstrap 5
    document.addEventListener('DOMContentLoaded', function () {
        var editProfileForm = new bootstrap.Modal(document.getElementById('editProfileForm'), {
            keyboard: false,
            backdrop: 'static'
        });
        editProfileForm.show();
    });

    document.getElementById('closeButton').addEventListener('click', function () {
        // Redirect to the specific page
        window.location.href = '/ManageProfiles/ManageProfilesPage';
    });
</script>

ValleyVisionSolution/Pages/ManageProfiles/ManageProfilesPage.cshtml
@page
@model ValleyVisionSolution.Pages.ManageProfiles.ManageProfilesPageModel
@{
    ViewData["Title"] = "Users";
    ViewData["HeaderTitle"] = "ManageUsers";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">

<style>
    .tableHeader {
        background-color: #274c77;
        color: white;
        vertical-align: middle !important;
    }

    .populatebtn { /* Style specifically for the populate button */
        padding: 10px 15px; /* Smaller padding for a smaller button */
        background-color: #6c757d; /* Bootstrap's secondary button color for differentiation */
        color: white;
    }

    .btn-unpublish {
        background-color: #274c77; /* Dark blue background */
        color: white; /* White text */
        border: none; /* No border */
    }

        .btn-unpublish:hover {
            background-color: #6096BA !important; /* Lighter blue on hover */
            color: white; /* Keep text white on hover */
        }

</style>

    <br />
    <table class="table table-bordered table-striped table-responsive table-hover">
        <thead class="tableHeader">
            <tr>
                <th>Username</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>User Type</th>
                <th>Street </th>
                <th>Apartment</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Country</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var profile in Model.FullProfileList)
                {
                    <tr>
                        <td>@profile.UserName</td>
                        <td>@profile.FirstName</td>
                        <td>@profile.LastName</td>
                        <td>@profile.Email</td>
                        <td>@profile.Phone</td>
                        <td>@profile.UserType</td>
                        <td>@profile.Street</td>
                        <td>@profile.Apartment</td>
                        <td>@profile.City</td>
                        <td>@profile.State</td>
                        <td>@profile.Zip</td>
                        <td>@profile.Country</td>
                        <td>
                        <a type="submit" class="btn btn-sm btn-light" asp-page="EditProfilesPage" style="align-content: center; display:inline-flex;" asp-route-userid="@profile.UserID">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <form method="post" onsubmit="return confirm('Are you sure you want to delete this user?')" style="align-content: center; display:inline-flex;" asp-route-userid=" @profile.UserID" asp-page-handler="DeleteProfile">
                            <button type="submit" class="btn btn-danger btn-sm custom-margin-left;">
                                <i class="bi bi-trash"></i> 
                            </button>
                        </form>
                        </td>
                    </tr>
                }
            }
        </tbody>

    </table>
    <br />
    <button class="btn btn-unpublish" style=" background-color:#2e4c74; -webkit-text-fill-color:white;" data-bs-toggle="modal" data-bs-target="#addProfileForm">Add User</button>



    <!-- Add New Profile Form -->
    <div class="modal fade" id="addProfileForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <form method="post" asp-page="/ManageProfilesPage">
                    <input type="hidden" name="triggeredBy" id="triggeredBy" value="">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Add User</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div>Username: </div>
                                <input asp-for="@Model.NewProfile.UserName" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.UserName"></span>
                            </div>
                            <div class="col-md-6">
                                <div>Password: </div>
                                <input asp-for="@Model.NewProfile.Password" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.Password"></span>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div>First Name: </div>
                                <input asp-for="@Model.NewProfile.FirstName" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.FirstName"></span>
                            </div>
                            <div class="col-md-6">
                                <div>Last Name: </div>
                                <input asp-for="@Model.NewProfile.LastName" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.LastName"></span>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div>Email: </div>
                                <input asp-for="@Model.NewProfile.Email" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.Email"></span>
                            </div>
                            <div class="col-md-6">
                                <div>Phone: </div>
                                <input asp-for="@Model.NewProfile.Phone" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.Phone"></span>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div>User Type: </div>
                            <select asp-for="@Model.NewProfile.UserType" class="form-select">
                                <option value="User">User</option>
                                <option value="Admin">Admin</option>
                            </select>
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.UserType"></span>
                            </div>
                            <div class="col-md-6">
                                <div>Street: </div>
                                <input asp-for="@Model.NewProfile.Street" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.Street"></span>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div>Apartment: </div>
                                <input asp-for="@Model.NewProfile.Apartment" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.Apartment"></span>
                            </div>
                            <div class="col-md-6">
                                <div>City: </div>
                                <input asp-for="@Model.NewProfile.City" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.City"></span>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div>State: </div>
                                <input asp-for="@Model.NewProfile.State" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.State"></span>
                            </div>
                            <div class="col-md-6">
                                <div>Zip: </div>
                                <input asp-for="@Model.NewProfile.Zip" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.Zip"></span>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div>Country: </div>
                                <input asp-for="@Model.NewProfile.Country" type="text" class="form-control">
                                <span class="text-danger" asp-validation-for="@Model.NewProfile.Country"></span>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer" style="border-top:none">
                        <button type="submit" class="btn btn-primary" asp-page-handler="NewProfile">Add User</button>
                        <button class="btn btn-secondary" asp-page="/ManageProfiles/ManageProfilesPage" asp-page-handler="PopulateHandler" formnovalidate>Populate</button>
                    </div>
                    
                    </form>
            </div>
        </div>
    </div>
    <!-- End New Profile Form -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const shouldOpenModal = '@Model.OpenAddProfileModal'.toLowerCase() === 'true';
        console.log("Modal should open:", shouldOpenModal); // Debug to see if the value is passed correctly

        if (shouldOpenModal) {
            var modal = new bootstrap.Modal(document.getElementById('addProfileForm'));
            modal.show();
        }
    });
</script>

ValleyVisionSolution/Pages/ManageProfiles/SingleProfilePage.cshtml
@page
@model ValleyVisionSolution.Pages.ManageProfiles.ProfilePageModel
@{
    ViewData["Title"] = "Profile";
}

<style>
    body, html {
        height: 100%;
        font-family: Arial, sans-serif;
        background-color: #f4f4f4; /* Optional: adds a background color to the whole page */
    }

    .profile-image {
        width: 120px;
        height: 120px;
        border-radius: 50%;
        border: 2px solid #dee2e6; /* Light grey border */
        object-fit: cover;
        margin-bottom: 20px;
    }

    .profile-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-top: 20px;
    }

    .info-container, .contact-container {
        display: flex;
        background-color: #f8f9fa;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 20px;
        margin-bottom: 20px;
        width: 80%;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    }

    .title {
        width: 50px; /* Fixed width for icon column */
        font-size: 2rem; /* Larger icon size */
        text-align: center; /* Center icon horizontally */
        margin-right: 10px; /* Space between icon and text */
    }

    .details {
        flex-grow: 1; /* Takes up remaining space */
    }

    .item {
        margin-bottom: 5px;
    }
</style>

<body>
    <div class="profile-container">
        @if (Model.profileInformation != null)
        {


            <div class="info-container">
                <div class="title"><i class="bi bi-person-circle"></i></div>
                <div class="details">
                    <div><strong>Account</strong></div>
                    <div class="item"><strong>First Name:</strong> @Model.profileInformation.FirstName</div>
                    <div class="item"><strong>Last Name:</strong> @Model.profileInformation.LastName</div>
                    <div class="item"><strong>User Type:</strong> @Model.profileInformation.UserType</div>
                    <div class="item"><strong>Username:</strong> @Model.profileInformation.UserName</div>
                </div>
            </div>

            <div class="contact-container">
                <div class="title"><i class="bi bi-envelope-fill"></i></div>
                <div class="details">
                    <div><strong>Contact</strong></div>
                    <div class="item"><strong>Address:</strong> @Model.profileInformation.Street @Model.profileInformation.Apartment @Model.profileInformation.City @Model.profileInformation.State @Model.profileInformation.Zip @Model.profileInformation.Country</div>
                    <div class="item"><strong>Phone:</strong> @Model.profileInformation.Phone</div>
                    <div class="item"><strong>Email:</strong> @Model.profileInformation.Email</div>
                </div>
            </div>
        }
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">
</body>