ValleyVisionSolution/Pages/ProposedDevelopments/DevelopmentPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.VisualBasic;
using System.Data.SqlClient;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;


namespace ValleyVisionSolution.Pages.ProposedDevelopments
{
    public class DevelopmentPageModel : PageModel
    {
        public List<FileMeta> DevFilesList { get; set; }
        public string DevName { get; set; }
        public string DevDescription { get; set; }
        public string DevImpactLevel { get; set; }
        public DateTime UploadTime { get; set; }
        public List<FileMeta> EconFileList { get; set; }

        [BindProperty]
        public List<int> NewDevelopmentFiles { get; set; }

        public DevelopmentPageModel() 
        { 

            DevFilesList = new List<FileMeta>();
            EconFileList = new List<FileMeta>();

        }


        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("LoggedIn") == "True" )
            {
                loadData();
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }
        }

        public void loadData()
        {
            int? devID = HttpContext.Session.GetInt32("devID");
            int initID = HttpContext.Session.GetInt32("InitID") ?? 0;

            SqlDataReader reader2 = DBClass.DevelopmentReader2((int)devID);
            while (reader2.Read())
            {
                DevName = reader2["devName"].ToString();
                DevDescription = reader2["devDescription"].ToString() ;
                DevImpactLevel = reader2["devImpactLevel"].ToString();
                UploadTime = Convert.ToDateTime(reader2["uploadedDateTime"]);

            }
            DBClass.ValleyVisionConnection.Close();

            SqlDataReader reader3 = DBClass.DevDetailsReader((int)devID);
            while (reader3.Read())
            {
                DevFilesList.Add(new FileMeta
                {
                    FileMetaID = int.Parse(reader3["fileMetaID"].ToString()),
                    FileName_ = reader3["fileName_"].ToString(),
                    FilePath = reader3["filePath"].ToString(),
                    FileType = reader3["fileType"].ToString(),
                    UploadedDateTime = Convert.ToDateTime(reader3["uploadedDateTime"]),
                    FirstName = reader3["firstName"].ToString(),
                    LastName = reader3["lastName"].ToString()
                });
            }
            DBClass.ValleyVisionConnection.Close();


            SqlDataReader reader = DBClass.ProposedDevelopmentFileReader(devID, initID);
            while (reader.Read())
            {
                EconFileList.Add(new FileMeta
                {
                    FileMetaID = int.Parse(reader["fileMetaID"].ToString()),
                    FileName_ = reader["fileName_"].ToString(),
                    FilePath = reader["filePath"].ToString(),
                    FileType = reader["fileType"].ToString(),
                    UploadedDateTime = Convert.ToDateTime(reader["uploadedDateTime"])
                });
            }
            DBClass.ValleyVisionConnection.Close();


        }

        public IActionResult OnPostAddDevelopmentFiles()
        {
            if (!ModelState.IsValid)
            {
                // Model state is not valid, return the page with validation errors
                loadData();
                return Page();
            }

            var devID = HttpContext.Session.GetInt32("devID");
            DBClass.AddDevelopmentFiles((int)devID, NewDevelopmentFiles);
            loadData();
            ModelState.Clear();
            NewDevelopmentFiles = new List<int>();
            return RedirectToPage("/ProposedDevelopments/DevelopmentPage");



            //TempData["FilesAdded"] = "true";
            //// Redirect to the same or another page to show the updated list of files


        }

        public IActionResult OnPostDeleteDevelopmentFiles(int fileMetaID) 
        {
            if (!ModelState.IsValid)
            {
                // Model state is not valid, return the page with validation errors
                loadData();
                return Page();
            }

            var devID = HttpContext.Session.GetInt32("devID");
            DBClass.DeleteDevelopmentFiles((int)devID, fileMetaID);
            loadData();
            //ModelState.Clear();
            return RedirectToPage("/ProposedDevelopments/DevelopmentPage");

        }

        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }


    }
}

ValleyVisionSolution/Pages/ProposedDevelopments/EditDevelopments.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;

namespace ValleyVisionSolution.Pages.ProposedDevelopments
{
    public class EditDevelopmentsModel : PageModel
    {
        [BindProperty]
        public DevelopmentArea EditedDev { get; set; }
        [BindProperty]
        public List<int> EditedDevUsers { get; set; }

        public EditDevelopmentsModel()
        {
            EditedDev = new DevelopmentArea();
            EditedDevUsers = new List<int>();
        }

        public void loadData()
        {
            int? devID = HttpContext.Session.GetInt32("devID");

            //Populate AllDevs list
            SqlDataReader reader = DBClass.DevelopmentReader2((int)devID);
            while (reader.Read())
            {
                EditedDev = new DevelopmentArea
                {
                    devID = Int32.Parse(devID.ToString()),
                    devName = reader["devName"].ToString(),
                    devDescription = reader["devDescription"].ToString(),
                    devImpactLevel = reader["devImpactLevel"].ToString(),
                    uploadedDateTime = Convert.ToDateTime(reader["uploadedDateTime"]),
                    userID = Int32.Parse(reader["userID"].ToString())
                };
            }
            // Close your connection in DBClass
            DBClass.ValleyVisionConnection.Close();
        }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("LoggedIn") == "True")
            {
                int? devID = HttpContext.Session.GetInt32("devID");
                HttpContext.Session.SetInt32("EditedDevID", (int)devID);
                loadData();
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }
        }

        public IActionResult OnPostUpdateDev()
        {
            if (!ModelState.IsValid)
            {
                // Model state is not valid, return the page with validation errors
                loadData();
                return Page();
            }
            int? devID = HttpContext.Session.GetInt32("devIDZ");
            // Model state is valid, continue with processing
            DBClass.EditDev(EditedDev);
            return RedirectToPage("/ProposedDevelopments/ProposedDevelopmentsPage");
        }

        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }
    }
}

ValleyVisionSolution/Pages/ProposedDevelopments/ProposedDevelopmentsPage.cshtml.cs
using DocumentFormat.OpenXml.EMMA;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration.UserSecrets;
using System.Data.SqlClient;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;

namespace ValleyVisionSolution.Pages.ProposedDev
{
    public class ProposedDevPageModel : PageModel
    {
        public List<DevelopmentArea> HighImpact { get; set; }
        public List<DevelopmentArea> MidImpact { get; set; }
        public List<DevelopmentArea> LowImpact { get; set; }
        [BindProperty]
        public DevelopmentArea NewDevelopmentArea { get; set; }

        public bool openaddProposedDevelopment { get; set; }

        public ProposedDevPageModel() 
        {
            HighImpact = new List<DevelopmentArea>();
            MidImpact = new List<DevelopmentArea>();
            LowImpact = new List<DevelopmentArea>();
            openaddProposedDevelopment = false;
        }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("LoggedIn") == "True")
            {
                loadData();
                
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }

        }

        public void loadData()
        {
            try
            {
                using (var reader = DBClass.DevelopmentReader())
                {
                    while (reader.Read())
                    {
                        var development = new DevelopmentArea
                        {
                            devID = int.Parse(reader["devID"].ToString()),
                            devName = reader["devName"].ToString(),
                            devDescription = reader["devDescription"].ToString(),
                            devImpactLevel = reader["devImpactLevel"].ToString(), // Fixed this line
                            uploadedDateTime = Convert.ToDateTime(reader["uploadedDateTime"]),
                            userID = int.Parse(reader["userID"].ToString())
                            
                        };

                        switch (development.devImpactLevel)
                        {
                            case "High":
                                HighImpact.Add(development);
                                break;
                            case "Medium":
                                MidImpact.Add(development);
                                break;
                            case "Low":
                                LowImpact.Add(development);
                                break;
                        }
                    }
                } // Using block ensures the reader is closed even if an exception occurs
            }
            catch (Exception ex)
            {
                // Log the exception details
                // Consider showing an error message to the user if appropriate
            }
            finally
            {
                DBClass.ValleyVisionConnection.Close();
            }

        }

        public IActionResult OnPostNewDevelopmentArea()
        {
            if (!ModelState.IsValid)
            {
                // Model state is not valid, return the page with validation errors
                openaddProposedDevelopment = true;
                loadData();
                return Page();
            }

            DBClass.AddDevelopmentArea(NewDevelopmentArea, HttpContext.Session.GetInt32("UserID"));
            loadData();
            ModelState.Clear();

            NewDevelopmentArea = new DevelopmentArea();

            return Page();
        }

        public IActionResult OnPostViewDetails(int devID)
        {
            HttpContext.Session.SetInt32("devID", devID);

            // Redirect to the DevelopmentPage
            return RedirectToPage("/ProposedDevelopments/DevelopmentPage");
        }

        public IActionResult OnPostEdit(int devID) 
        {
            HttpContext.Session.SetInt32("devID", devID);
            return RedirectToPage("/ProposedDevelopments/EditDevelopments");
        }


        public IActionResult OnPostDelete(int devid)
        {
            DBClass.DeleteDevelopmentArea(devid);
            return RedirectToPage("/ProposedDevelopments/ProposedDevelopmentsPage");
        }


        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }

    }
}

ValleyVisionSolution/Pages/ProposedDevelopments/UploadDev.cshtml.cs
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;
using ValleyVisionSolution.Services;

namespace ValleyVisionSolution.Pages.ProposedDevelopments
{
    public class UploadDevModel : PageModel
    {

        private readonly IBlobService _blobService;

        public UploadDevModel(IBlobService blobService)
        {
            _blobService = blobService;
        }


        public void OnGet()
        {
            TempData["ShowModal"] = true;
        }

        public async Task<IActionResult> OnPostAsync(IFormFile file)
        {
            int initID = HttpContext.Session.GetInt32("InitID") ?? 0;
            if (file != null && file.Length > 0)
            {
                // Generate a unique file name to avoid overwriting existing files
                var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                var fileExtension = Path.GetExtension(file.FileName);
                var uniqueFileName = fileName + DateTime.Now.ToString("yyyyMMddHHmmss") + fileExtension;

                // Use the IBlobService to upload the file
                using (var fileStream = file.OpenReadStream())
                {
                    await _blobService.UploadFileBlobAsync(uniqueFileName, fileStream, file.ContentType);
                }

                // Prepare the file metadata
                var fileMeta = new FileMeta
                {
                    FileName_ = fileName + fileExtension,
                    FilePath = uniqueFileName,
                    FileType = fileExtension,
                    UploadedDateTime = DateTime.Now,
                    userID = HttpContext.Session.GetInt32("UserID")
                };

                // Update the database with the file metadata
                int? devID = HttpContext.Session.GetInt32("devID");
                DBClass.UploadDevFile(initID, fileMeta, devID);


                return RedirectToPage("/ProposedDevelopments/DevelopmentPage");
            }

            ViewData["ErrorMessage"] = "You must select a file.";
            return Page();
        }
    }
}

ValleyVisionSolution/Pages/ProposedDevelopments/DevelopmentPage.cshtml
@page
@model ValleyVisionSolution.Pages.ProposedDevelopments.DevelopmentPageModel
@{
    ViewData["Title"] = "Development Files";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css">
<script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>


<style>
    /* Extended theme and consistent styling */
    :root {
        --primary-color: #274c77; /* Navy blue */
        --light-gray: #d3d4d5;
        --hover-light-gray: #eaeaea;
        --focus-ring-color: rgba(39, 76, 119, 0.5);
    }

    .btn-primary, .btn-secondary {
        background-color: var(--primary-color) !important;
        color: white !important;
        border-color: var(--primary-color);
    }

        .btn-primary:hover, .btn-secondary:hover {
            background-color: var(--hover-light-gray) !important;
            color: var(--primary-color) !important;
            border-color: var(--primary-color);
        }

    /* Adjusting the card header to match the theme */
    .card-header, .coleur {
        background-color: var(--primary-color); /* Ensuring the card header matches the theme */
        color: white; /* White text for readability */
    }

    /* Button alignment and spacing */
    .button-container {
        display: flex;
        justify-content: end; /* Aligns buttons to the right */
        margin-bottom: 20px;
    }

    .table-hover tbody tr:hover {
        background-color: var(--hover-light-gray);
    }

    .table {
        border-collapse: collapse; /* Ensure borders collapse into a single line */
    }

        .table th, .table td {
            border: 1px solid #dee2e6; /* Bootstrap’s default border color for tables */
        }

        .table .text-center {
            text-align: center; /* Centering content in the 'Actions' column */
        }

    .table-hover thead tr, .table-hover tbody tr {
        border-bottom: 1px solid #dee2e6; /* Adds a bottom border to each row for clarity */
    }

    .choices__list--multiple .choices__item {
        display: inline-block;
        vertical-align: middle;
        border-radius: 20px;
        padding: 4px 10px;
        font-size: 12px;
        font-weight: 500;
        margin-right: 3.75px;
        margin-bottom: 3.75px;
        background-color: #274c77;
        border: 1px solid #d3d3d3;
        color: #fff;
        word-break: break-all;
        box-sizing: border-box;
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">

@* <div class="container">
    <div class="button-container">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#ecoDevFilesModal">Add Resources from Economic Development</button>
        <a href="UploadDev">
            <button type="button" class="btn btn-secondary">Upload File</button>
        </a>
    </div>
</div> *@

<div class="container">
    <div class="button-container">
        <button type="button" class="btn btn-primary me-2" data-bs-toggle="modal" data-bs-target="#ecoDevFilesModal">Add Resources from Economic Development</button>
        <a href="UploadDev">
            <button type="button" class="btn btn-secondary">Upload File</button>
        </a>
    </div>
</div>


<!-- Script for redirecting remains the same -->
<script>
    function redirectToDevelopmentPage() {
        window.location.href = '/ProposedDevelopments/EditDevelopments';
    }
</script>

<!-- Ensuring the main content is wrapped in a 'container' for consistency -->
<div class="container my-4">
    <div class="card">
        <div class="card-header">
            <!-- Adjusted to use .card-header for clarity -->
            <h3>@Model.DevName Proposed Development Information</h3>
        </div>
        <div class="card-body">
            <p class="card-text">@Model.DevDescription</p>
            <p class="card-text">Impact Level: <strong>@Model.DevImpactLevel</strong></p>
            <p class="card-text">Date Founded: @Model.UploadTime.ToString("MM/dd/yyyy")</p>
        </div>
    </div>
</div>
<style>
    .table {
        border-collapse: collapse; /* Ensure borders collapse into a single line */
    }

        .table th, .table td {
            border: 1px solid #dee2e6; /* Bootstrap’s default border color for tables */
        }

        /* Centering content in the 'Actions' column */
        .table .text-center {
            text-align: center;
        }

    /* Adjusting table header background and text color */
    .coleur {
        background-color: #274c77; /* Your primary color */
        color: white;
    }

    /* Ensuring all table rows and headers have borders */
    .table-hover thead tr, .table-hover tbody tr {
        border-bottom: 1px solid #dee2e6; /* Adds a bottom border to each row */
    }
</style>

<div class="container mt-3">
    <table class="table table-hover">
        <thead class="coleur">
            <tr>
                <th scope="col">File Name</th>
                <th scope="col">File Type</th>
                <th scope="col">Uploaded By</th>
                <th scope="col">Uploaded Date</th>
                <th scope="col" class="text-center">Actions</th> <!-- Ensure header is also centered -->
            </tr>
        </thead>
        <tbody>
            @foreach (var file in Model.DevFilesList)
            {
                <tr>
                    <td>@file.FileName_</td>
                    <td>@file.FileType</td>
                    <td>@file.FirstName @file.LastName</td>
                    <td>@file.UploadedDateTime.ToString("MM/dd/yyyy")</td>
                    <td class="text-center">
                        <a href="@Url.Content(file.FilePath)" class="btn btn-secondary btn-sm d-inline-block action-form" download><i class="bi bi-download"></i></a>
                        <form method="post" asp-page-handler="DeleteDevelopmentFiles" class="d-inline action-form" onsubmit="return confirm('Are you sure you want to remove @file.FileName_ from this development area?')">
                            <input type="hidden" name="FileMetaID" value="@file.FileMetaID" />
                            <button type="submit" class="btn btn-danger btn-sm"><i class="bi bi-x"></i></button>
                        </form>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

<style>
    .btn-light {
        background-color: white !important;
        border-color: lightgrey;
        color: black !important;
    }

        .btn-check:focus + .btn-light, .btn-light:focus {
            color: #000;
            background-color: #f9fafb;
            border-color: #f9fafb;
            box-shadow: 0 0 0 0.25rem rgba(211,212,213,.5);
        }

        .btn-light:hover {
            border-color: lightgrey;
        }
</style>


<!-- Modal for adding files to the proposed development -->
<div class="modal fade" id="ecoDevFilesModal" tabindex="-1" aria-labelledby="ecoDevFilesModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" asp-page="/DevelopmentPage">
                <div class="modal-header">
                    <h5 class="modal-title" id="ecoDevFilesModalLabel">Select Files to Add</h5>
                    <button type="button" class="btn-close" id="closebutton" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="col-md-6">
                        <div>Select Files</div>
                        <select asp-for="@Model.NewDevelopmentFiles" class="form-select form-control" multiple data-live-search="true" style="height:38px">
                            @{
                                foreach (var file in Model.EconFileList)
                                {
                                    <option value="@file.FileMetaID">@file.FileName_</option>
                                }
                            }
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" asp-page-handler="AddDevelopmentFiles">Add Selected Files</button>
                </div>
            </form>
        </div>
     </div>
</div> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script>
    $(document).ready(function () {
        var filesAdded = '@TempData["FilesAdded"]';
        if (filesAdded === "true") {
            $('#ecoDevFilesModal').modal('hide'); // Close the modal
        }
    });
</script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var selectElements = document.querySelectorAll('.form-select');
        selectElements.forEach(function (el) {
            new Choices(el, {
                removeItemButton: true,
                searchEnabled: true,
                shouldSort: false
            });
        });
    });
</script>
<script>
    // JavaScript to handle redirection on modal close
    document.getElementById('closebutton').addEventListener('click', function () {
        window.location.href = '/ProposedDevelopments/DevelopmentPage';
    });
</script>

ValleyVisionSolution/Pages/ProposedDevelopments/EditDevelopments.cshtml
@page
@model ValleyVisionSolution.Pages.ProposedDevelopments.EditDevelopmentsModel
@using DevelopmentArea = ValleyVisionSolution.Pages.DataClasses.DevelopmentArea;
@{
    ViewData["Title"] = "Edit";
}

<style>
    .btn-light {
        background-color: white !important;
        border-color: lightgrey;
        color: black !important;
    }

        .btn-check:focus + .btn-light, .btn-light:focus {
            color: #000;
            background-color: #f9fafb;
            border-color: #f9fafb;
            box-shadow: 0 0 0 0.25rem rgba(211,212,213,.5);
        }

        .btn-light:hover {
            border-color: lightgrey;
        }
</style>

<!-- Edit Task Form -->
<div class="modal fade" id="editDevForm" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form method="post" asp-page="/DevelopmentPage">
                <input type="hidden" name="triggeredBy" id="triggeredBy" value="">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Development View</h5>
                    <button type="button" class="btn-close" id="closeButton" data-bs-dismiss="modal" aria-label="Close">
                    </button>
                </div>
                <div class="modal-body">

                    <input type="hidden" asp-for="@Model.EditedDev.devID">

                    <div class="row mb-3">
                        <div class="col-md-6">
                            <div>Development Name:</div>
                            <input asp-for="@Model.EditedDev.devName" type="text" class="form-control" value="@Model.EditedDev.devName">
                            <span class="text-danger" asp-validation-for="@Model.EditedDev.devName"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        
                        <div class="col-md-6">
                            <div>Impact Level:</div>
                            <select class="form-select" asp-for="@Model.EditedDev.devImpactLevel" id="devImpactLevel">
                                @if (Model.EditedDev.devImpactLevel == "Low")
                                {
                                    <option value="Low" selected>Low</option>
                                    <option value="Medium">Medium</option>
                                    <option value="High">High</option>
                                }
                                @if (Model.EditedDev.devImpactLevel == "Medium")
                                {
                                    <option value="Low">Low</option>
                                    <option value="Medium" selected>Medium</option>
                                    <option value="High">High</option>
                                }
                                @if (Model.EditedDev.devImpactLevel == "High")
                                {
                                    <option value="Low">Low</option>
                                    <option value="Medium">Medium</option>
                                    <option value="High" selected>High</option>
                                }
                               
                            </select>
                            <span class="text-danger" asp-validation-for="@Model.EditedDev.devImpactLevel"></span>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-12">
                            <div>Description:</div>
                            <textarea asp-for="@Model.EditedDev.devDescription" class="form-control" id="devDescription" rows="3" maxlength="250"></textarea>
                            <span class="text-danger" asp-validation-for="@Model.EditedDev.devDescription"></span>
                        </div>
                    </div>

                </div>
                <div class="modal-footer" style="border-top:none">
                    <button type="submit" class="btn btn-primary" asp-page-handler="UpdateDev">Update</button>
                </div>
            </form>

        </div>
    </div>
</div>
<!-- End Edit Task Form -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var editDevForm = new bootstrap.Modal(document.getElementById('editDevForm'), {
            keyboard: false,
            backdrop: 'static'
        });
        editDevForm.show();
    });

    document.getElementById('closeButton').addEventListener('click', function () {
        // Redirect to the specific page
        window.location.href = '/ProposedDevelopments/ProposedDevelopmentsPage';
    });
</script>

ValleyVisionSolution/Pages/ProposedDevelopments/UploadDev.cshtml
@page
@model ValleyVisionSolution.Pages.ProposedDevelopments.UploadDevModel
@{
}

<style>
    .btn-light {
        background-color: white !important;
        border-color: lightgrey;
        color: black !important;
    }

        .btn-check:focus + .btn-light, .btn-light:focus {
            color: #000;
            background-color: #f9fafb;
            border-color: #f9fafb;
            box-shadow: 0 0 0 0.25rem rgba(211,212,213,.5);
        }

        .btn-light:hover {
            border-color: lightgrey;
        }
</style>


<!-- File Upload Modal -->
<form method="post" enctype="multipart/form-data" asp-page="/DevelopmentPage">
    <div class="modal fade" id="uploadFileModal" tabindex="-1" aria-labelledby="uploadFileModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="uploadFileModalLabel">Upload File</h5>
                    <button type="button" class="btn-close" id="closebutton" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="file" name="file" class="form-control" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" id="closeModalButton" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" asp-page-handler="Upload">Upload</button>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Check if the ShowModal flag is set
            var showModal = '@TempData["ShowModal"]' === 'True';

            if (showModal) {
                // Use Bootstrap's modal method to show the modal
                var modal = new bootstrap.Modal(document.getElementById('uploadFileModal'));
                modal.show();
            }
        });
    </script>
    <script>
        // JavaScript to handle redirection on modal close
        document.getElementById('closebutton').addEventListener('click', function () {
            window.location.href = '/ProposedDevelopments/DevelopmentPage';
        });

        document.getElementById('closeModalButton').addEventListener('click', function () {
            window.location.href = '/ProposedDevelopments/DevelopmentPage';
        });
    </script>
}



<!-- End Edit Task Form -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>