ValleyVisionSolution/Pages/Resources/AdminResources.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;
using ValleyVisionSolution.Services;

namespace ValleyVisionSolution.Pages.Resources
{
    public class AdminResourcesModel : PageModel
    {
        public List<FileMeta> ResourceList { get; set; } = new List<FileMeta>();
        public List<FileMeta> FileUpload { get; set; } = new List<FileMeta> { };
        public List <Initiative> InitativeList { get; set; } = new List<Initiative>();
        public string CurrentInitiativeName { get; set; }
        public List<FileMeta> PublishedFiles { get; set; } = new List<FileMeta>();

        private readonly IBlobService _blobService;
        public AdminResourcesModel(IBlobService blobService)
        {
            _blobService = blobService;
        }


        public void loadData(string searchTerm = null)
        {
            int? UserID = HttpContext.Session.GetInt32("UserID");

            SqlDataReader reader2 = DBClass.InitiativesReader((int)UserID);
            while (reader2.Read())
            {
                InitativeList.Add(new Initiative
                {
                    InitID = int.Parse(reader2["initID"].ToString()),
                    InitName = reader2["initName"].ToString()
                });
            }
            DBClass.ValleyVisionConnection.Close();

            foreach (Initiative init in InitativeList)
            {
                using (var reader = DBClass.ResourceReader((int)init.InitID))
                {
                    while (reader.Read())
                    {
                        ResourceList.Add(new FileMeta
                        {
                            FileMetaID = int.Parse(reader["FileMetaID"].ToString()),
                            FileName_ = reader["FileName_"].ToString(),
                            FilePath = reader["FilePath"].ToString(),
                            FileType = reader["FileType"].ToString(),
                            UploadedDateTime = Convert.ToDateTime(reader["UploadedDateTime"]),
                            userID = int.Parse(reader["userID"].ToString()),
                            FirstName = reader["firstName"].ToString(),
                            LastName = reader["lastName"].ToString(),
                            published = reader["published"].ToString(),
                            InitiativeName = init.InitName
                        });
                    }
                    DBClass.ValleyVisionConnection.Close();
                } 
            }



            if (!string.IsNullOrEmpty(searchTerm))
            {
                searchTerm = searchTerm.ToLower();
                ResourceList = ResourceList.Where(file =>
                    file.FileName_.ToLower().Contains(searchTerm) ||
                    file.FileType.ToLower().Contains(searchTerm) ||
                    file.UploadedDateTime.ToString().ToLower().Contains(searchTerm) ||
                    $"{file.FirstName} {file.LastName}".ToLower().Contains(searchTerm) ||
                    file.InitiativeName.ToLower().Contains(searchTerm)
                ).ToList();
            }
        }


        public IActionResult OnGet(string searchTerm)
        {
            HttpContext.Session.Remove("InitName");
            int initID = HttpContext.Session.GetInt32("InitID") ?? 0;
            if (HttpContext.Session.GetString("LoggedIn") == "True")
            {
                loadData(searchTerm); // Pass searchTerm to loadData
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }
        }


        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }


        public IActionResult OnPostPublishFileAsync(int fileId)
        {
            DBClass.PublishFile(fileId);
            return RedirectToPage(); // Redirect back to the same page to refresh the list and show the updated publish status
        }

        public IActionResult OnPostUnpublishFileAsync(int fileId)
        {
            DBClass.UnPublishFile(fileId);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetDownloadFileAsync(string filePath, string fileName)
        {
            // Assuming 'filePath' is the unique blob name used when the file was uploaded
            Stream blobStream = await _blobService.DownloadFileBlobAsync(filePath);

            if (blobStream == null)
            {
                return NotFound();
            }

            // Determine the content type
            // You might want to have a better way to determine the content type based on the file extension
            string contentType = "application/octet-stream";

            // Return the file to the user
            // 'fileName' is the original file name that the user uploaded
            return File(blobStream, contentType, fileName);
        }

        public async Task<IActionResult> OnPostDeleteFileAsync(int fileId, string filePath)
        {
            // Since 'filePath' should contain the unique blob name,
            // use the IBlobService to delete the file from Azure Blob Storage
            await _blobService.DeleteFileBlobAsync(filePath);

            // Now delete the record from the database
            DBClass.DeleteFile(fileId);

            // Redirect back to the page to refresh the list of files
            return RedirectToPage();
        }


        public class DeleteRequest
        {
            public int FileId { get; set; }
        }



    }
}

ValleyVisionSolution/Pages/Resources/ResourcesPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using Microsoft.AspNetCore.Http;
using System.Data.SqlClient;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;
using System.IO;
using System.Threading.Tasks;
using ValleyVisionSolution.Services;
using System.Collections.Generic;
using System.Linq;

namespace ValleyVisionSolution.Pages.Resources
{
    public class ResourcesPageModel : PageModel
    {
        public List<FileMeta> ResourceList { get; set; } = new List<FileMeta>();
        public List<FileMeta> FileUpload { get; set; } = new List<FileMeta>();
        public string CurrentInitiativeName { get; set; }

        private readonly IBlobService _blobService;

        // Modified to include IBlobService through Dependency Injection
        public ResourcesPageModel(IBlobService blobService)
        {
            _blobService = blobService;
        }





        public void loadData(int initID, string searchTerm = null)
        {
            int? UserID = HttpContext.Session.GetInt32("UserID");

            SqlDataReader reader = DBClass.ResourceReader((int)initID);
            while (reader.Read())
            {
                ResourceList.Add(new FileMeta
                {
                    FileMetaID = int.Parse(reader["FileMetaID"].ToString()),
                    FileName_ = reader["FileName_"].ToString(),
                    FilePath = reader["FilePath"].ToString(),
                    FileType = reader["FileType"].ToString(),
                    UploadedDateTime = Convert.ToDateTime(reader["UploadedDateTime"]),
                    userID = int.Parse(reader["userID"].ToString()),
                    FirstName = reader["firstName"].ToString(),
                    LastName = reader["lastName"].ToString(),
                    published = reader["published"].ToString()
                });
            }
            DBClass.ValleyVisionConnection.Close();

            if (!string.IsNullOrEmpty(searchTerm))
            {
                searchTerm = searchTerm.ToLower();
                ResourceList = ResourceList.Where(file =>
                    file.FileName_.ToLower().Contains(searchTerm) ||
                    file.FileType.ToLower().Contains(searchTerm) ||
                    file.UploadedDateTime.ToString().ToLower().Contains(searchTerm) ||
                    $"{file.FirstName} {file.LastName}".ToLower().Contains(searchTerm)
                ).ToList();
            }
        }


        public IActionResult OnGet(string searchTerm)
        {
            int initID = HttpContext.Session.GetInt32("InitID") ?? 0;
            if (HttpContext.Session.GetString("LoggedIn") == "True")
            {
                loadData(initID, searchTerm); // Pass searchTerm to loadData
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }
        }


        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnPostAsync(IFormFile file)
        {
            int initID = HttpContext.Session.GetInt32("InitID") ?? 0;
            if (file != null && file.Length > 0)
            {
                // Generate a unique file name to avoid overwriting existing files
                var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                var fileExtension = Path.GetExtension(file.FileName);
                var uniqueFileName = fileName + DateTime.Now.ToString("yyyyMMddHHmmss") + fileExtension;

                // Use the IBlobService to upload the file
                using (var fileStream = file.OpenReadStream())
                {
                    await _blobService.UploadFileBlobAsync(uniqueFileName, fileStream, file.ContentType);
                }

                // Prepare the file metadata
                var fileMeta = new FileMeta
                {
                    FileName_ = fileName + fileExtension,
                    FilePath = uniqueFileName,
                    FileType = fileExtension,
                    UploadedDateTime = DateTime.Now,
                    userID = HttpContext.Session.GetInt32("UserID")
                };

                // Update the database with the file metadata
                DBClass.UploadFile(initID, fileMeta);

                return RedirectToPage("./ResourcesPage");
            }

            ViewData["ErrorMessage"] = "You must select a file.";
            return Page();
        }

        public IActionResult OnPostPublishFileAsync(int fileId)
        {
            DBClass.PublishFile(fileId);
            return RedirectToPage(); // Redirect back to the same page to refresh the list and show the updated publish status
        }

        public IActionResult OnPostUnpublishFileAsync(int fileId)
        {
            DBClass.UnPublishFile(fileId);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetDownloadFileAsync(string filePath, string fileName)
        {
            // Assuming 'filePath' is the unique blob name used when the file was uploaded
            Stream blobStream = await _blobService.DownloadFileBlobAsync(filePath);

            if (blobStream == null)
            {
                return NotFound();
            }

            // Determine the content type
            // You might want to have a better way to determine the content type based on the file extension
            string contentType = "application/octet-stream";

            // Return the file to the user
            // 'fileName' is the original file name that the user uploaded
            return File(blobStream, contentType, fileName);
        }


        public async Task<IActionResult> OnPostDeleteFileAsync(int fileId, string filePath)
        {
            // Since 'filePath' should contain the unique blob name,
            // use the IBlobService to delete the file from Azure Blob Storage
            await _blobService.DeleteFileBlobAsync(filePath);

            // Now delete the record from the database
            DBClass.DeleteFile(fileId);

            // Redirect back to the page to refresh the list of files
            return RedirectToPage();
        }

        public class DeleteRequest
        {
            public int FileId { get; set; }
        }



    }
}

ValleyVisionSolution/Pages/Resources/AdminResources.cshtml
@page
@model ValleyVisionSolution.Pages.Resources.AdminResourcesModel
@{
    ViewData["Title"] = "Resources";
    ViewData["AdminR"] = "True";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">

<style>
    .custom-margin-left {
        margin-left: 10px;
    }

    .tableHeader {
        background-color: #274c77;
        color: white;
        vertical-align: middle !important;
    }

    .bg-custom-blue {
        background-color: #274c77;
    }

    .clear-search {
        margin-top: 20px; /* Adjust as necessary */
        margin-bottom: 20px;
    }

    .btn-unpublish {
        background-color: #274c77; /* Dark blue background */
        color: white; /* White text */
        border: none; /* No border */
    }

        .btn-unpublish:hover {
            background-color: #6096BA; /* Lighter blue on hover */
            color: white; /* Keep text white on hover */
        }

</style>

<div class="container mt-4">
    <div class="resource-container mb-4">
        <!-- Add bottom margin to the resource container -->
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
            <!-- Search form -->
            <form method="get" class="search-form" style="flex-grow: 1; display: flex; margin-right: 10px;">
                <input type="text" name="searchTerm" placeholder="Search files..." class="form-control mr-2" style="flex-grow: 1;" />
                <button type="submit" class="btn btn-primary custom-margin-left">Search</button>
            </form>

        </div>

        @if (!string.IsNullOrEmpty(HttpContext.Request.Query["searchTerm"]))
        {
            <div class="clear-search">
                <a href="@Url.Page("./AdminResources")" style="background-color:gray; border-radius:6px" class="text-white fs-6 p-2 position-relative !importants">
                    Clear search: @HttpContext.Request.Query["searchTerm"] <i class="bi bi-x-circle"></i>
                </a>
            </div>
        }

    <!-- Resource Table -->
    <table class="table table-bordered table-striped table-responsive table-hover">
        <thead class="tableHeader">
            <tr>
                <th>File Name</th>
                <th>Initiative</th>
                <th>Uploaded Date</th>
                <th>Uploaded By</th>
                <th>Published</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var fileMeta in Model.ResourceList)
            {
                <tr>
                    <td>@fileMeta.FileName_</td>
                    <td>@fileMeta.InitiativeName</td>
                    <td>@fileMeta.UploadedDateTime.ToString("MM/dd/yy hh:mm tt")</td>
                    <td>@fileMeta.FirstName @fileMeta.LastName</td>
                    <td>@(string.IsNullOrEmpty(fileMeta.published) || fileMeta.published.Equals("no", StringComparison.OrdinalIgnoreCase) ? "No" : (fileMeta.published.Equals("yes", StringComparison.OrdinalIgnoreCase) ? "Yes" : "No"))</td>
                    <td>
                            <a asp-page-handler="DownloadFile"
                               asp-route-filePath="@fileMeta.FilePath"
                               asp-route-fileName="@fileMeta.FileName_"
                               class="btn btn-secondary btn-sm" style="margin-left:6px;">
                                <i class="bi bi-download"></i>
                            </a>
                        <form method="post" style="display: inline-block;"
                              asp-page-handler="DeleteFile"
                              asp-route-fileId="@fileMeta.FileMetaID"
                              asp-route-filePath="@fileMeta.FilePath"
                              onsubmit="return confirm('Are you sure you want to delete this file?');">
                                <button type="submit" class="btn btn-danger btn-sm custom-margin-left" style="margin-left:0px !important;">
                                <i class="bi bi-trash"></i>
                            </button>
                        </form>
                            @if (fileMeta.published == "yes")
                            {
                                <form method="post" style="display: inline-block;" asp-page-handler="UnpublishFile" asp-route-fileId="@fileMeta.FileMetaID" onsubmit="return confirm('Are you sure you want to unpublish this file? It will no longer be accessible to the public.');">
                                    <button type="submit" class="btn btn-unpublish btn-sm custom-margin-left" style="margin-top:3px; margin-left:0px;">
                                        <i class="bi bi-cloud-download"></i> Un-Publish
                                    </button>
                                </form>
                            }
                            else
                            {
                                <form method="post" style="display: inline-block; margin-top:3px; margin-left:0px;" asp-page-handler="PublishFile" asp-route-fileId="@fileMeta.FileMetaID" onsubmit="return confirm('Are you sure you want to publish this file to the public? Anyone will be able to access this file without logging in');">
                                    <button type="submit" class="btn btn-light btn-sm custom-margin-left" style="margin-top:3px; margin-left:0px;">
                                        <i class="bi bi-cloud-upload"></i> Publish
                                    </button>
                                </form>
                            }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<!-- File Upload Modal -->
<form method="post" enctype="multipart/form-data" asp-page-handler="Upload">
    <div class="modal fade" id="uploadFileModal" tabindex="-1" aria-labelledby="uploadFileModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="uploadFileModalLabel">Upload File</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="file" name="file" class="form-control" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>
            </div>
        </div>
    </div>
</form>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

ValleyVisionSolution/Pages/Resources/ResourcesPage.cshtml
@page
@model ValleyVisionSolution.Pages.Resources.ResourcesPageModel
@{
    ViewData["Title"] = "Resources";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

<style>
    .custom-margin-left {
        margin-left: 10px;
    }

    .tableHeader {
        background-color: #274c77;
        color: white;
        vertical-align: middle !important;
    }

    .bg-custom-blue {
        background-color: #274c77;
    }

    .clear-search {
        margin-top: 20px; /* Adjust as necessary */
        margin-bottom: 20px;
    }

    .btn-unpublish {
        background-color: #274c77; /* Dark blue background */
        color: white; /* White text */
        border: none; /* No border */
    }

        .btn-unpublish:hover {
            background-color: #6096BA; /* Lighter blue on hover */
            color: white; /* Keep text white on hover */
        }

</style>

<div class="resource-container">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
        <!-- Search form -->
        <form method="get" class="search-form" style="flex-grow: 1; display: flex; margin-right: 10px;">
            <input type="text" name="searchTerm" placeholder="Search files..." class="form-control mr-2" style="flex-grow: 1;" />
            <button type="submit" class="btn btn-primary custom-margin-left">Search</button>
        </form>

        <!-- Upload File Modal Trigger Button -->
        <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#uploadFileModal">Upload File</button>
    </div>

    @if (!string.IsNullOrEmpty(HttpContext.Request.Query["searchTerm"]))
    {
        @if (!string.IsNullOrEmpty(HttpContext.Request.Query["searchTerm"]))
        {
            <div class="clear-search">
                <a href="@Url.Page("./ResourcesPage")" style="background-color:gray; border-radius:6px" class="text-white fs-6 p-2 position-relative !importants">
                    Clear search: @HttpContext.Request.Query["searchTerm"] <i class="bi bi-x-circle"></i>
                </a>
            </div>
        }

    }

    <!-- Resource Table -->
    <table class="table table-bordered table-striped table-responsive table-hover">
        <thead class="tableHeader">
            <tr>
                <th>File Name</th>
                <th>File Type</th>
                <th>Uploaded Date</th>
                <th>Uploaded By</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var fileMeta in Model.ResourceList)
            {
                <tr>
                    <td>@fileMeta.FileName_</td>
                    <td>@fileMeta.FileType</td>
                    <td>@fileMeta.UploadedDateTime.ToString("MM/dd/yy hh:mm tt")</td>
                    <td>@fileMeta.FirstName @fileMeta.LastName</td>
                    <td>
                        <a asp-page-handler="DownloadFile"
                           asp-route-filePath="@fileMeta.FilePath"
                           asp-route-fileName="@fileMeta.FileName_"
                           class="btn btn-secondary btn-sm">
                            <i class="bi bi-download"></i>
                        </a>
@*                         <a href="@Url.Content(fileMeta.FilePath)" download="@fileMeta.FileName_" class="btn btn-outline-secondary btn-sm">
                            <i class="bi bi-download"></i>
                        </a> *@
                        <form method="post" style="display: inline-block;"
                              asp-page-handler="DeleteFile"
                              asp-route-fileId="@fileMeta.FileMetaID"
                              asp-route-filePath="@fileMeta.FilePath"
                              onsubmit="return confirm('Are you sure you want to delete this file?');">
                            <button type="submit" class="btn btn-danger btn-sm custom-margin-left">
                                <i class="bi bi-trash"></i>
                            </button>
                        </form>
                        @if (fileMeta.published == "yes")
                        {
                            <form method="post" style="display: inline-block;" asp-page-handler="UnpublishFile" asp-route-fileId="@fileMeta.FileMetaID" onsubmit="return confirm('Are you sure you want to unpublish this file? It will no longer be accessible to the public.');">
                                <button type="submit" class="btn btn-unpublish btn-sm custom-margin-left">
                                    <i class="bi bi-cloud-download"></i> Un-Publish
                                </button>
                            </form>
                        }
                        else
                        {
                            <form method="post" style="display: inline-block;" asp-page-handler="PublishFile" asp-route-fileId="@fileMeta.FileMetaID" onsubmit="return confirm('Are you sure you want to publish this file to the public? Anyone will be able to access this file without logging in');">
                                <button type="submit" class="btn btn-light btn-sm custom-margin-left">
                                    <i class="bi bi-cloud-upload"></i> Publish
                                </button>
                            </form>
                        }

                        @* <form method="post" style="display: inline-block;" asp-page-handler="PublishFile" asp-route-fileId="@fileMeta.FileMetaID" onsubmit="return confirm('Are you sure you want to publish this file to the public? Anyone will be able to access this file without logging in');">
                            <button type="submit" class="btn btn-light btn-sm custom-margin-left">
                                <i class="bi bi-cloud-upload"></i>
                            </button>
                        </form> *@
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<!-- File Upload Modal -->
<form method="post" enctype="multipart/form-data" asp-page-handler="Upload">
    <div class="modal fade" id="uploadFileModal" tabindex="-1" aria-labelledby="uploadFileModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="uploadFileModalLabel">Upload File</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="file" name="file" class="form-control" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>
            </div>
        </div>
    </div>
</form>