ValleyVisionSolution/Pages/HistoricalSpending/EditDataPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Bibliography;

namespace ValleyVisionSolution.Pages.HistoricalSpending
{
    public class EditDataPageModel : PageModel
    {
        [BindProperty]
        public Expenditure ExpenditureToUpdate{ get; set; }

        public bool OpenEditDataModal { get; set; } = true;

        public EditDataPageModel()
        {
            ExpenditureToUpdate = new Expenditure();
        }
        
        public void loadData()
        {
            SqlDataReader singleExpenditureYear = DBClass.singleExpenditureReader(HttpContext.Session.GetInt32("Year"));
            while (singleExpenditureYear.Read())
            {
                ExpenditureToUpdate.Year = Int32.Parse(singleExpenditureYear["year_"].ToString());
                ExpenditureToUpdate.InflationRate = Convert.ToDecimal(singleExpenditureYear["inflationRate"].ToString());
                ExpenditureToUpdate.InterestRate = Convert.ToDecimal(singleExpenditureYear["interestRate"].ToString());
                ExpenditureToUpdate.PublicSafety = Convert.ToDecimal(singleExpenditureYear["publicSafety"].ToString());
                ExpenditureToUpdate.School = Convert.ToDecimal(singleExpenditureYear["school"].ToString());
                ExpenditureToUpdate.Anomaly = Convert.ToDecimal(singleExpenditureYear["anomaly"].ToString());
                ExpenditureToUpdate.Other = Convert.ToDecimal(singleExpenditureYear["other"].ToString());

            }
            DBClass.ValleyVisionConnection.Close();
        }

        public IActionResult OnGet(int Year)
        {
            if (HttpContext.Session.GetString("LoggedIn") == "True")
            {
                HttpContext.Session.SetInt32("Year", Year);
                loadData();
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }
        }

        public IActionResult OnPostEditData()
        {
            int? year = HttpContext.Session.GetInt32("Year");
            DBClass.EditHistoricSpendingData(ExpenditureToUpdate, (int)year);
            DBClass.ValleyVisionConnection.Close();
            return RedirectToPage("/HistoricalSpending/ViewDataPage");
        }

        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }



    }
}

ValleyVisionSolution/Pages/HistoricalSpending/ViewDataPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;

namespace ValleyVisionSolution.Pages.HistoricalSpending
{
    public class ViewDataPageModel : PageModel
    {

        public List<Expenditure> HistoricalExpenditureDataList { get; set; }
        public bool OpenAddDataModal { get; set; }

        [BindProperty]
        public Expenditure NewHistoricalSpendingData { get; set; }


        public ViewDataPageModel()
        {
            HistoricalExpenditureDataList = new List<Expenditure>();
            OpenAddDataModal = false; //keeps the modal open on page reload if input validations were not successful
        }

        public void loadData()
        {
            SqlDataReader reader = DBClass.HistoricalExpendituresReader();
            while (reader.Read())
            {

                HistoricalExpenditureDataList.Add(new Expenditure
                {
                    Year = int.Parse(reader["Year_"].ToString()),
                    InflationRate = Decimal.Parse(reader["InflationRate"].ToString()),
                    InterestRate = Decimal.Parse(reader["InterestRate"].ToString()),
                    PublicSafety = Decimal.Parse(reader["PublicSafety"].ToString()),
                    School = Decimal.Parse(reader["School"].ToString()),
                    Anomaly = Decimal.Parse(reader["Anomaly"].ToString()),
                    Other = Decimal.Parse(reader["Other"].ToString()),
                    TotalExpenditure = Decimal.Parse(reader["TotalExpenditure"].ToString())
                });
            }
            // Close your connection in DBClass
            DBClass.ValleyVisionConnection.Close();
        }


        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("LoggedIn") == "True")
            {
                loadData();
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }
        }

        public IActionResult OnPostDelete(int year)
        {
            DBClass.DeleteHistoricalSpendData(year);
            return RedirectToPage("/HistoricalSpending/ViewDataPage");
        }

        public IActionResult OnPostNewData()
        {
            if (!ModelState.IsValid)
            {
                // Model state is not valid, return the page with validation errors
                loadData();
                OpenAddDataModal = true;
                return Page();
            }

            // Model state is valid, continue with processing
            DBClass.AddHistoricalSpendingData(NewHistoricalSpendingData);
            loadData();
            ModelState.Clear();
            NewHistoricalSpendingData = new Expenditure();
            return Page();
        }

        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }
    }

}

ValleyVisionSolution/Pages/RevenueProjection/EditDataPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using DocumentFormat.OpenXml.Spreadsheet;

namespace ValleyVisionSolution.Pages.RevenueProjection
{
    public class EditDataPageModel : PageModel
    {

        [BindProperty]
        public Revenue RevenueToUpdate { get; set; }

        public EditDataPageModel()
        {
            RevenueToUpdate = new Revenue();
        }

        public void loadData()
        {
            SqlDataReader singleRevenueYear = DBClass.SingleRevenueDataReader(HttpContext.Session.GetInt32("Year"));
            while (singleRevenueYear.Read())
            {
                RevenueToUpdate.Year = Int32.Parse(singleRevenueYear["year_"].ToString());
                RevenueToUpdate.RealEstateTax = Convert.ToDecimal(singleRevenueYear["realEstateTax"].ToString());
                RevenueToUpdate.PersonalPropertyTax = Convert.ToDecimal(singleRevenueYear["personalPropertyTax"].ToString());
                RevenueToUpdate.FeesLicensesTax = Convert.ToDecimal(singleRevenueYear["feesLicensesTax"].ToString());
                RevenueToUpdate.StateFunding = Convert.ToDecimal(singleRevenueYear["otherRevenue"].ToString());

            }
            DBClass.ValleyVisionConnection.Close();

        }

        public void OnGet(int Year)
        {
            HttpContext.Session.SetInt32("Year", Year);
            loadData();
        }

        public IActionResult OnPost()
        {
            DBClass.EditRevenueData(RevenueToUpdate);
            DBClass.ValleyVisionConnection.Close();
            return RedirectToPage("/RevenueProjection/ViewDataPage");
        }

        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }

    }
}

ValleyVisionSolution/Pages/RevenueProjection/RevenueProjectionPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;
using System;
using System.Data.SqlClient;
using ValleyVisionSolution.Pages.DataClasses;
using ValleyVisionSolution.Pages.DB;
using ClosedXML.Excel;
using ValleyVisionSolution.Services;
using System.Collections.Generic;

namespace ValleyVisionSolution.Pages.RevenueProjection
{
    public class RevenueProjectionPageModel : PageModel
    {
        public Revenue LatestRevenue = new Revenue();
        public List<Revenue> ProjectedRevenues { get; set; } = new List<Revenue>();
        public bool DefaultLoad = true;



        [BindProperty]
        public decimal RealEstateTaxGrowth { get; set; }
        [BindProperty]
        public decimal PersonalPropertyTaxGrowth { get; set; }
        [BindProperty]
        public decimal FeesLicensesTaxGrowth { get; set; }
        [BindProperty]
        public decimal StateFundingAmount { get; set; }
        [BindProperty]
        public int NumProjectionYears { get; set; }

        private readonly IBlobService _blobService;

        public RevenueProjectionPageModel(IBlobService blobService)
        {

            _blobService = blobService;

        }

        public void loadData()
        {
            //Populate current year revenue data
            SqlDataReader reader = DBClass.LatestRevenueYearReader();
            if (reader.Read())
            {
                LatestRevenue = new Revenue
                {
                    Year = int.Parse(reader["Year_"].ToString()),
                    RealEstateTax = Decimal.Parse(reader["RealEstateTax"].ToString()),
                    PersonalPropertyTax = Decimal.Parse(reader["PersonalPropertyTax"].ToString()),
                    FeesLicensesTax = Decimal.Parse(reader["FeesLicensesTax"].ToString()),
                    StateFunding = Decimal.Parse(reader["OtherRevenue"].ToString()),
                    TotalRevenue = Decimal.Parse(reader["TotalRevenue"].ToString())
                };
            }
            // Close your connection in DBClass
            DBClass.ValleyVisionConnection.Close();
        }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("LoggedIn") == "True")
            {
                loadData();
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }
        }

        public IActionResult OnPostRunProjection()
        {
            loadData();

            ProjectedRevenues.Add(new Revenue
            {
                RealEstateTax = LatestRevenue.RealEstateTax,
                PersonalPropertyTax = LatestRevenue.PersonalPropertyTax,
                FeesLicensesTax = LatestRevenue.FeesLicensesTax,
                StateFunding = LatestRevenue.StateFunding,
                TotalRevenue = LatestRevenue.TotalRevenue,
                Year = LatestRevenue.Year
            });

            // Calculate projections for subsequent years
            for (int i = 1; i <= NumProjectionYears; i++)
            {
                ProjectedRevenues.Add(new Revenue
                {
                    RealEstateTax = Math.Round(ProjectedRevenues[i - 1].RealEstateTax * (1 + (RealEstateTaxGrowth / 100)), 2),
                    PersonalPropertyTax = Math.Round(ProjectedRevenues[i - 1].PersonalPropertyTax * (1 + (PersonalPropertyTaxGrowth / 100)), 2),
                    FeesLicensesTax = Math.Round(ProjectedRevenues[i - 1].FeesLicensesTax * (1 + (FeesLicensesTaxGrowth / 100)), 2),
                    StateFunding = Math.Round(StateFundingAmount, 2),
                    Year = ProjectedRevenues[i - 1].Year + 1,
                    TotalRevenue = Math.Round((ProjectedRevenues[i - 1].RealEstateTax * (1 + (RealEstateTaxGrowth / 100))) +
                        (ProjectedRevenues[i - 1].PersonalPropertyTax * (1 + (PersonalPropertyTaxGrowth / 100))) +
                        (ProjectedRevenues[i - 1].FeesLicensesTax * (1 + (FeesLicensesTaxGrowth / 100))) +
                        (StateFundingAmount), 2)

                });

               
            }
            HttpContext.Session.SetString("ProjectedRevenues", JsonSerializer.Serialize(ProjectedRevenues));
            DefaultLoad = false;

            return Page();
        }
        public string GetChartDataAsJson()
        {
            return JsonSerializer.Serialize(ProjectedRevenues);
        }
        

        public async Task<IActionResult> OnPostDownloadExcel()
        {
            if (HttpContext.Session.GetString("ProjectedRevenues") != null)
            {
                ProjectedRevenues = JsonSerializer.Deserialize<List<Revenue>>(HttpContext.Session.GetString("ProjectedRevenues"));

                Stream templateStream = await _blobService.DownloadFileBlobAsync("RevenueProjectionsTemplate.xlsx");
                if (templateStream == null)
                {
                    TempData["Error"] = "The template could not be found in Blob Storage.";
                    return Page();
                }

                using (var stream = new MemoryStream())
                {
                    await templateStream.CopyToAsync(stream);
                    stream.Position = 0; // Reset the stream position to the beginning

                    using (var workbook = new XLWorkbook(stream)) // Load the workbook from the stream
                    {
                        IXLWorksheet worksheet = workbook.Worksheets.Worksheet(2); // Use the appropriate worksheet

                        int currentRow = 2; // Start populating data from this row onwards

                        foreach (var revenue in ProjectedRevenues)
                        {
                            worksheet.Cell(currentRow, 1).Value = revenue.Year;
                            worksheet.Cell(currentRow, 2).Value = revenue.RealEstateTax;
                            worksheet.Cell(currentRow, 3).Value = revenue.PersonalPropertyTax;
                            worksheet.Cell(currentRow, 4).Value = revenue.FeesLicensesTax;
                            worksheet.Cell(currentRow, 5).Value = revenue.StateFunding;
                            worksheet.Cell(currentRow, 6).Value = revenue.TotalRevenue;
                            currentRow++;
                        }

                        worksheet.Columns().AdjustToContents();

                        using (var outputStream = new MemoryStream())
                        {
                            workbook.SaveAs(outputStream);
                            outputStream.Position = 0; // Reset for reading
                            return File(outputStream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "RevenueProjections.xlsx");
                        }
                    }
                }
            }
            else
            {
                TempData["ErrorMessage"] = "Please run the projection before downloading the report.";
                return RedirectToPage("/RevenueProjection/RevenueProjectionPage");
            }
        }




        public async Task<IActionResult> OnPostSaveExcel()
        {
            if (HttpContext.Session.GetString("ProjectedRevenues") != null)
            {
                ProjectedRevenues = JsonSerializer.Deserialize<List<Revenue>>(HttpContext.Session.GetString("ProjectedRevenues"));
            }
            else
            {
                loadData();
                return Page();
            }

            var uniqueFileName = $"RevenueProjections_{DateTime.Now:MMdd_HHmmss}.xlsx";

            // Attempt to download the Excel template as a stream from Azure Blob Storage
            Stream templateStream = await _blobService.DownloadFileBlobAsync("RevenueProjectionsTemplate.xlsx");
            if (templateStream == null)
            {
                TempData["Error"] = "The template could not be found in Blob Storage.";
                return Page();
            }

            using (var seekableStream = new MemoryStream())
            {
                await templateStream.CopyToAsync(seekableStream);
                seekableStream.Position = 0; // Ensure the stream is at the beginning before reading it

                using (var workbook = new XLWorkbook(seekableStream)) // Load the workbook from the stream
                {
                    IXLWorksheet worksheet = workbook.Worksheets.Worksheet(2); // Use the appropriate worksheet

                    int currentRow = 2; // Adjust based on your template's starting row for data

                    // Populate the worksheet with data from ProjectedRevenues
                    foreach (var revenue in ProjectedRevenues)
                    {
                        worksheet.Cell(currentRow, 1).Value = revenue.Year;
                        worksheet.Cell(currentRow, 2).Value = revenue.RealEstateTax;
                        worksheet.Cell(currentRow, 3).Value = revenue.PersonalPropertyTax;
                        worksheet.Cell(currentRow, 4).Value = revenue.FeesLicensesTax;
                        worksheet.Cell(currentRow, 5).Value = revenue.StateFunding;
                        worksheet.Cell(currentRow, 6).Value = revenue.TotalRevenue;
                        currentRow++;
                    }

                    worksheet.Columns().AdjustToContents();

                    using (var outputStream = new MemoryStream())
                    {
                        workbook.SaveAs(outputStream);
                        outputStream.Position = 0; // Ready the stream for uploading

                        // Upload the filled workbook to Azure Blob Storage
                        await _blobService.UploadFileBlobAsync(uniqueFileName, outputStream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
                    }
                }
            }

            // Update your database with the file's details

ValleyVisionSolution/Pages/RevenueProjection/EditDataPage.cshtml
@page
@model ValleyVisionSolution.Pages.RevenueProjection.EditDataPageModel
@using Revenue = ValleyVisionSolution.Pages.DataClasses.Revenue;
@{
    ViewData["Title"] = "Edit Revenue";
}

<!-- Edit Revenue Data Form -->
<div class="modal fade" id="editRevenueDataForm" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form method="post" asp-page="/EditDataPage">
                <input type="hidden" name="triggeredBy" id="triggeredBy" value="">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Edit Annual Revenue Data</h5>
                    <button type="button" class="btn-close" id="closeButton" data-bs-dismiss="modal" aria-label="Close">
                    </button>
                </div>
                <div class="modal-body">

                    <input type="hidden" asp-for="@Model.RevenueToUpdate.Year">
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <div>Real Estate Property Tax:</div>
                            <input asp-for="@Model.RevenueToUpdate.RealEstateTax" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.RevenueToUpdate.RealEstateTax"></span>
                        </div>
                        <div class="col-md-6">
                            <div>Personal Property Tax:</div>
                            <input asp-for="@Model.RevenueToUpdate.PersonalPropertyTax" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.RevenueToUpdate.PersonalPropertyTax"></span>
                        </div>
                        <div class="col-md-6">
                            <div>Fees & Licenses Tax: </div>
                            <input asp-for="@Model.RevenueToUpdate.FeesLicensesTax" type="text" class="form-control" />
                            <span class="text-danger" asp-validation-for="@Model.RevenueToUpdate.FeesLicensesTax"></span>
                        </div>
                        <div class="col-md-6">
                            <div>State Funding: </div>
                            <input asp-for="@Model.RevenueToUpdate.StateFunding" type="int" class="form-control">
                            <span class="text-danger" asp-validation-for="@Model.RevenueToUpdate.StateFunding"></span>
                        </div>
                    </div>
                    <div class="modal-footer" style="border-top:none">
                        <button type="submit" class="btn btn-primary" asp-page-handler="UpdateRevenueData">Update</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
<!-- End Edit Revenue Data Form -->



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var editRevenueDataForm = new bootstrap.Modal(document.getElementById('editRevenueDataForm'), {
            keyboard: false,
            backdrop: 'static'
        });
        editRevenueDataForm.show();
    });

    document.getElementById('closeButton').addEventListener('click', function () {
        // Redirect to the specific page
        window.location.href = '/RevenueProjection/ViewDataPage';
    });
</script>

ValleyVisionSolution/Pages/RevenueProjection/RevenueProjectionPage.cshtml
@page
@model ValleyVisionSolution.Pages.RevenueProjection.RevenueProjectionPageModel
@using Newtonsoft.Json
@{
    ViewData["Title"] = "Revenue Projection";
    var jsonData = JsonConvert.SerializeObject(Model.ProjectedRevenues);
}
<!-- Include Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

<style>
    .parameterTitle {
        position: relative; 
        display: inline-block; 
        cursor: pointer; 
        font-size: 12.5px; 
    }

    .chart-grid{
        display:grid;
        grid-template-columns:1fr 1fr;
        grid-template-rows:auto auto;
        grid-template-areas: 
        "ChartA ChartB"
        "ChartC ChartD";
        gap:2vw;
    }
    #chartA{
        grid-area:ChartA;
    }

    #chartB {
        grid-area: ChartB;
    }

    #chartC {
        grid-area: ChartC;
    }

    #chartD {
        grid-area: ChartD;
    }

    .dashboard-tile {
        font-size: max(1.25vw, 10px);
    }

    .dashboard-tile-title-bar {
        position: relative;
        background-color: #274C77;
        width: 100%;
        height: 1.75em;
        display: flex;
        align-items: center;
        text-wrap: nowrap;
    }

    .dashboard-tile-title {
        position: absolute;
        left: 50%;
        transform: translateX(-50%);
        margin: 0;
        color: #fff;
        font-size:0.85vw;
    }

    .dashboard-tile-contents {
        padding: 3%;
        background-color: #f2f2f2;        
    }

    .parameterTitle {
        position: relative; 
        display: inline-block; 
        font-size: .75vw;
    }

    .custom-tooltip {
        visibility: hidden;
        width: 200px;
        background-color: white;
        color: black;
        text-align: center;
        border-radius: 6px;
        padding: 5px 0;
        position: absolute;
        z-index: 1;
        bottom: 125%; 
        left: 50%;
        margin-left: -100px; 
        box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.1); 
    }

    .parameterTitle:hover .custom-tooltip {
        visibility: visible; 
    }

</style>

<form method="post" asp-page="/RevenueProjectionPage">
    <div class="row mb-3">
        <div class="col-md-2">
            <div class="parameterTitle">
                <span><i class="bi bi-question-circle"></i></span> Real Estate Tax Growth %:
                <span class="custom-tooltip">Enter the expected growth percentage for real estate taxes. (ie. 0.03 = 3; for a 3% increase in growth)</span> 
            </div>
            <input asp-for="@Model.RealEstateTaxGrowth" type="text" class="form-control">
        </div>

        <div class="col-md-2">
            <div class="parameterTitle">
                <span><i class="bi bi-question-circle"></i></span> Personal Property Tax Growth %:
                <span class="custom-tooltip">Enter the expected growth percentage for personal property taxes. Do not include symbols. (ie. 0.05 = 5; for a 5% increase in growth)</span> 
            </div>
            <input asp-for="@Model.PersonalPropertyTaxGrowth" type="text" class="form-control">
        </div>

        <div class="col-md-2">
            <div class="parameterTitle">
                <span><i class="bi bi-question-circle"></i></span> Fees & Licenses Tax Growth %:
                <span class="custom-tooltip">Enter the expected growth percentage for fees and licenses. (ie. 0.025 = 2.5; for a 2.5% increase in growth)</span> 
            </div>
            <input asp-for="@Model.FeesLicensesTaxGrowth" type="text" class="form-control">
        </div>

        <div class="col-md-2">
            <div class="parameterTitle">
                <span><i class="bi bi-question-circle"></i></span> Total State Funding Amount $:
                <span class="custom-tooltip">Enter the total amount of state funding available. (ie. 1,000,000)</span> 
            </div>
            <input asp-for="@Model.StateFundingAmount" type="text" class="form-control">
        </div>

        <div class="col-md-2">
            <div class="parameterTitle">
                <span><i class="bi bi-question-circle"></i></span> Number of Projection Years:
                <span class="custom-tooltip">Select the number of years for the revenue projection.</span> 
            </div>
            <select asp-for="@Model.NumProjectionYears" class="form-select form-control">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>

        <div class="col-md-2 d-flex flex-column justify-content-end align-items-end">
            <button type="submit" class="btn btn-primary" id="runProjectionBtn" asp-page-handler="RunProjection">Run Projection</button>
        </div>
    </div>
</form>


<div class="chart-grid">
    <div class="dashboard-tile" id="chartA">
        <div class="dashboard-tile-title-bar">
            <div class="dashboard-tile-title">
                Total Revenue Projection 
            </div>
        </div>
        <div class="dashboard-tile-contents">
            <canvas id="revenueChartA"></canvas>
        </div>
    </div>


    <div class="dashboard-tile" id="chartB">
        <div class="dashboard-tile-title-bar">
            <div class="dashboard-tile-title">Tax Category Projection </div>
        </div>
        <div class="dashboard-tile-contents">
            <canvas id="revenueChartB"></canvas>
            </div>
    </div>

    <div class="dashboard-tile" id="chartC">
        <div class="dashboard-tile-title-bar">
            <div class="dashboard-tile-title">Total Revenue Projection</div>
        </div>
        <div class="dashboard-tile-contents">
            <canvas id="revenueChartC"></canvas>
        </div>
    </div>

    <div class="dashboard-tile" id="chartD">
        <div class="dashboard-tile-title-bar">
            <div class="dashboard-tile-title">Tax Category Projection</div>
        </div>
        <div class="dashboard-tile-contents">
            <canvas id="revenueChartD"></canvas>
        </div>
    </div>
</div>
<br />
<div style="display:flex; justify-content:flex-end; gap: 10px;">
    <a href="/RevenueProjection/ViewDataPage" class="btn btn-primary" style="margin-right: 10px;">View Revenue Data</a>
    <form method="post" asp-page-handler="DownloadExcel">
        <button type="submit" class="btn btn-secondary">Download Report</button>
    </form>
    <form method="post" asp-page-handler="SaveExcel" style="margin-left: 10px;">
        <button type="submit" class="btn btn-primary">Save to Resources</button>
    </form>
</div>




<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>




<script>
 

    document.addEventListener('DOMContentLoaded', function () {
        var rawData = @Html.Raw(Model.GetChartDataAsJson());
        var allLabels = ['Real Estate Tax', 'Personal Property Tax', 'Fees Licenses Tax', 'State Funding', 'Total Revenue'];
        var colors = [
            'rgba(255, 190, 91, 1)',
            'rgba(96, 150, 186, 1)',
            'rgba(185, 209, 138, 1)',
            'rgba(174, 174, 212, 1)',
            'rgba(39, 76, 119, 1)'
        ];

        function createChart(chartId, type, labels, customColors = {}) {
            var datasets = labels.map((label, index) => {
                var color = customColors[label] || colors[index]; // Use custom color if available, otherwise use default
                return {
                    label: label,
                    data: rawData.map(item => item[label.replace(/\s+/g, '')]),
                    backgroundColor: color,
                    borderColor: color,
                    borderWidth: 2,
                    fill: type !== 'line'
                };
            });

            var ctx = document.getElementById(chartId).getContext('2d');
            return new Chart(ctx, {
                type: type,
                data: {
                    labels: rawData.map(item => item.Year.toString()),
                    datasets: datasets
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    },
                    plugins: {
                        legend: {
                            position: 'bottom'
                        }
                    }
                }
            });
        }

        // Specify custom colors for 'Total Revenue' in Chart A and Chart C
        var customColorSettings = { 'Total Revenue': 'rgba(96, 150, 186, 1)' };

        createChart('revenueChartA', 'bar', ['Total Revenue'], customColorSettings);
        createChart('revenueChartB', 'bar', allLabels.slice(0, -1)); // Exclude 'Total Revenue'
        createChart('revenueChartC', 'line', ['Total Revenue'], customColorSettings);
        createChart('revenueChartD', 'line', allLabels.slice(0, -1)); // Exclude 'Total Revenue'
    });

    
</script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
    @if (TempData["Message"] != null)
    {
        <text>
                                var message = JSON.parse('@Json.Serialize(TempData["Message"])');
            alert(message);
        </text>
    }
            });
</script>